site_name: QFlux Docs
repo_url: https://github.com/batistagroup/qflux
repo_name: batistagroup/qflux
copyright: CC-BY 4.0 &copy; 2025 Batista Group
theme:
  name: material
  logo: img/qflux-logo.png
  favicon: img/qflux_favicon.png
  features:
    - content.code.copy
    - navigation.footer
    - navigation.indexes
  palette:
      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css
  - stylesheets/collapse-sidebars.css

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/collapse-sidebars.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - toc:
      toc_depth: 3

plugins:
  - search
  - material-plausible
  - mkdocstrings:
      handlers:
        python:
          paths: [src]  # if your package is in a src folder (src-layout)


nav: # Note: All paths must be relative to the docs dir
  - Home: 'index.md'
  - Contribution Guide: 'CONTRIBUTING.md'
  - Closed Systems: # Directory Page
    - 'qflux/Closed_Systems/index.md' # Specifies landing page for directory
    # Subpages within the directory are indented, specified as key/value pairs
    - Anatomy of a Dynamics Simulation: 'qflux/Closed_Systems/basics.md'
    - The Quantum Harmonic Oscillator: 'qflux/Closed_Systems/qho_example.md'
    - Adenine-Thymine Base Pair: 'qflux/Closed_Systems/AT_basepair.md'
    - Spin Chain Simulation: 'qflux/Closed_Systems/spinchain.md'
    - Arbitrary Hamiltonian Dynamics: 'qflux/Closed_Systems/arbitrary_evo.md'
    - Source Code: 'qflux/Closed_Systems/cs_api.md'
  - Open Systems: 
    - 'qflux/Open_Systems/index.md'
    - Open System Dynamics Overview: 'qflux/Open_Systems/basics.md'
    - Spin Chain Demo: 'qflux/Open_Systems/spinchainOpen.md'
    - Spin 1/2 Demo: 'qflux/Open_Systems/spinhalfOpen.md'
    - Double Well Demo: 'qflux/Open_Systems/DoubleWellOpen.md'
    - Source Code: 'qflux/Open_Systems/os_api.md' 
  - Variational Methods: 
    - 'qflux/Variational_Methods/index.md'
    - VarQTE Demo: 'qflux/Variational_Methods/varQTE.md'
    - UAVQD for Open Systems: 'qflux/Variational_Methods/Vectorized_Adaptive.md'
    - SSE for Open Systems: 'qflux/Variational_Methods/trajectory_FMO.md'
  - GQME: 
    - 'qflux/GQME/index.md'
    - Introduction to GQME: 'qflux/GQME/What_is_GQME.md'
    - Introduction to TT-TFD: 'qflux/GQME/What_is_TTTFD.md'
    - GQME for Spin-Boson model: 'qflux/GQME/spin_boson_GQME.md'
    - Quantum Algorithms of GQME: 'qflux/GQME/quantum_GQME_dilation.md'
    - Source Code: 'qflux/GQME/gqme_api.md'
extra:
  analytics:
    provider: plausible
    domain: qflux.batistalab.com

    # : If using custom domain proxy or self-hosting Plausible,
    # : uncomment and specify script path here:
    src: "https://analytics.batistalab.com/js/script.js"

    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: good
          note: >-
            Thanks for your feedback!

        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: bad
          note: >-
            Thanks for your feedback!
